// Russian accusative case for "Виза в [страну]"
const ACCUSATIVE: Record<string, string> = {
  DE: 'Германию',
  FR: 'Францию',
  IT: 'Италию',
  ES: 'Испанию',
  CZ: 'Чехию',
  PL: 'Польшу',
  AT: 'Австрию',
  CH: 'Швейцарию',
  NL: 'Нидерланды',
  BE: 'Бельгию',
  PT: 'Португалию',
  GR: 'Грецию',
  HU: 'Венгрию',
  SK: 'Словакию',
  HR: 'Хорватию',
  FI: 'Финляндию',
  SE: 'Швецию',
  NO: 'Норвегию',
  DK: 'Данию',
  GB: 'Великобританию',
  TR: 'Турцию',
  AE: 'ОАЭ',
  JP: 'Японию',
  KR: 'Южную Корею',
  TH: 'Таиланд',
  CN: 'Китай',
  IN: 'Индию',
  ID: 'Индонезию',
  VN: 'Вьетнам',
  SG: 'Сингапур',
  MY: 'Малайзию',
  US: 'США',
  CA: 'Канаду',
  AU: 'Австралию',
  NZ: 'Новую Зеландию',
  MX: 'Мексику',
  GE: 'Грузию',
  BY: 'Беларусь',
  UA: 'Украину',
  AM: 'Армению',
  AZ: 'Азербайджан',
  KG: 'Кыргызстан',
  UZ: 'Узбекистан',
  EG: 'Египет',
  MA: 'Марокко',
  TN: 'Тунис',
  ZA: 'ЮАР',
  BR: 'Бразилию',
  AR: 'Аргентину',
}

// Returns "Германию" for DE, falls back to name_ru if not mapped
export function toAccusative(code: string, nameRu: string): string {
  return ACCUSATIVE[code.toUpperCase()] ?? nameRu
}
